# template to be extended by those pipelines that will run tests after a build.
parameters:

  - name: isPR
    displayName: State if the tests are ran for a PR build
    type: boolean
    default: false

  - name: provisionatorChannel
    displayName: Provisionator channel to use 
    type: string
    default: 'latest'

  - name: macOSName # comes from the build agent demand named macOS.Name
    displayName: Name of the version of macOS to use
    type: string
    default: 'Sequoia'

  - name: runTests
    displayName: Run Simulator Tests
    type: boolean
    default: true

  - name: runOldMacOSTests
    displayName: Run Tests on older macOS versions 
    type: boolean
    default: true

  - name: runWindowsIntegration
    displayName: Run Windows integration tests
    type: boolean
    default: true

resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true

    - repository: yaml-templates
      type: git
      name: xamarin.yaml-templates
      ref: refs/heads/main
      
    - repository: macios-adr
      type: git
      name: macios-adr
      ref: refs/heads/main

variables:
  - template: ../variables/common.yml
  - name: DisablePipelineConfigDetector
    value: true

stages:
  - template: ../tests-stage.yml
    parameters:
      xcodeChannel: Stable
      macOSName: ${{ parameters.macOSName }}
      isPR: ${{ parameters.isPR }}
      provisionatorChannel: ${{ parameters.provisionatorChannel }}
      runTests: ${{ parameters.runTests }}
      runWindowsIntegration: ${{ parameters.runWindowsIntegration }}
