# YAML pipeline build definition
# https://devdiv.visualstudio.com/DevDiv/_build?definitionId=17751
#
parameters:

- name: manuallyCreateLocPR
  type: boolean
  default: false

variables:
- template: templates/variables/common.yml

resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: true

  - repository: yaml-templates
    type: git
    name: xamarin.yaml-templates
    ref: refs/heads/main

trigger:
- main

schedules:

# Create the PR into main with the newest usable localization strings once a week on Sundays
- cron: "0 12 * * 0"
  displayName: Sunday Build
  branches:
    include:
    - main
  always: true

stages:
- stage: localization
  displayName: 'Localization'
  jobs:
  - job: translations
    displayName: 'Loc translations'
    pool:
      vmImage: windows-latest
    steps:
    - template:  templates/loc-translations.yml
      parameters:
        isPR: false
        repositoryAlias: self
        commit: HEAD
        createLocPR: ${{ or(eq(parameters.manuallyCreateLocPR, true), eq(variables['Build.Reason'], 'Schedule')) }}
