name: Autoformat code - push results
on:
  workflow_run:
    workflows: ["Autoformat code"]
    types:
      - completed

# This action needs the following permissions in order to push the results back to the original branch.
permissions:
  pull-requests: write
  contents: write

jobs:
  push-and-notify:
    name: Push autoformatted code and notify user
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Push autoformatted patch'
        uses: rolfbjarne/autoformat-push@v0.3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          git_user_email: 'github-actions-autoformatter@xamarin.com'
          git_user_name: 'GitHub Actions Autoformatter'
          commentOnPullRequest: false
